#!/usr/bin/env lua

local function main()
    local cmd = arg[1] or "cd"
    for path in io.stdin:lines() do
        print(path)
        os.execute(cmd.." '"..path.."' &>/dev/null")
    end
end

os.exit(main())
